on:
  push:
    branches:
      - main

jobs:
  upload_files:
    runs-on: ubuntu-latest
    name: Upload viz files
    env:
      sftp_host: ${{ secrets.SFTPHOST }}
      sftp_user: ${{ secrets.SFTPUSER }}
      sftp_password: ${{ secrets.SFTPPASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Upload Files
        id: upload
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: ${{ env.sftp_host }}
          port: 22
          username: ${{ env.sftp_user }}
          password: ${{ env.sftp_password }}
          localPath: './viz'
          remotePath: './sffoodsim.com'
