on:
  workflow_run:
    workflows: 
      - Tests
    branches:
      - main
    types: 
      - completed

jobs:
  upload_files:
    environment: deploy
    runs-on: ubuntu-latest
    name: Upload viz files
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Upload Files
        id: upload
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: ${{ secrets.SFTPHOST }}
          port: 22
          username: ${{ secrets.SFTPUSER }}
          password: ${{ secrets.SFTPPASSWORD }}
          localPath: './viz'
          remotePath: './foodsimsf.com'
