name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Requirements
        run: pip install -r requirements.txt
      - name: TestPrep
        run: pip install nose2
      - name: nose2
        run: nose2
      - name: MypyPrep
        run: pip install mypy
      - name: mypy
        run: mypy
